name: ptodolist
description: "매일 반복하는 루틴과 추가 할 일의 완료 여부를 추적하는 로컬 전용 모바일 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Local DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Charts
  fl_chart: ^0.70.2

  # Notifications
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.9.0+3

  # Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Home Widget
  home_widget: ^0.7.0

  # Fonts
  google_fonts: ^6.2.1

  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2

  # Backup / Export
  share_plus: ^10.1.2
  file_picker: ^8.1.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  freezed: ^2.5.7
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

  # Testing
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#B1F0CE"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true
